- name: Update the system
  command: sudo apt update

- name: Copy outputs.txt to the remote machine
  copy:
    src: "/var/lib/jenkins/workspace/one-click/ansible/outputs.txt"
    dest: "/tmp/outputs.txt"

- name: Read Terraform outputs file
  slurp:
    src: "/tmp/outputs.txt"
  register: terraform_outputs_raw

- name: Debug decoded Terraform outputs
  debug:
    msg: "{{ terraform_outputs_raw.content | b64decode }}"

- name: Parse Terraform outputs into variables
  set_fact:
    kafka_host: >
      {{
        (terraform_outputs_raw.content | b64decode).splitlines() | select('match', '^kafka-host') | map('split', ' ') | map('last') | first
      }}

- name: Debug Kafka host
  debug:
    msg: "Kafka host IP is {{ kafka_host }}"

- name: Ensure Kafka dependencies are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-11-jdk

- name: Download Kafka
  get_url:
    url: "{{ kafka_download_url }}"
    dest: /tmp/kafka.tgz

- name: Extract Kafka
  unarchive:
    src: /tmp/kafka.tgz
    dest: /opt/
    remote_src: yes

- name: Ensure Kafka config and data directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ kafka_config_dir }}"
    - "{{ kafka_data_dir }}"

- name: Generate a cluster ID using kafka-storage.sh
  command: >
    /opt/kafka_{{ kafka_version }}/bin/kafka-storage.sh random-uuid
  register: kraft_uuid

- name: Create Kafka KRaft configuration from template
  template:
    src: kafka-config.j2
    dest: "{{ kafka_config_dir }}/server.properties"
  vars:
    kraft_uuid: "{{ kraft_uuid.stdout }}"

- name: Format KRaft metadata directory
  command: >
    /opt/kafka_{{ kafka_version }}/bin/kafka-storage.sh format
    --config {{ kafka_config_dir }}/server.properties
    --cluster-id {{ kraft_uuid.stdout }} --ignore-formatted
  args:
    creates: "{{ kafka_data_dir }}/meta.properties"

- name: Create systemd service for Kafka
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
  notify:
    - reload kafka

- name: Reload systemd to register Kafka service
  command: systemctl daemon-reload

- name: Enable Kafka service to start on boot
  command: systemctl enable kafka

- name: Start Kafka service
  command: systemctl start kafka

- name: Add Kafka to PATH
  lineinfile:
    path: /etc/profile
    line: 'export PATH=$PATH:/opt/kafka_{{ kafka_version }}/bin'
    create: yes

- name: Create Kafka topic "finnhub"
  command: >
    /opt/kafka_{{ kafka_version }}/bin/kafka-topics.sh
    --create
    --bootstrap-server {{ kafka_host }}:{{ kafka_port }}
    --topic finnhub
    --partitions 1
    --replication-factor 1
  args:
    creates: "{{ kafka_data_dir }}/topic-finnhub"

- name: Reload profile to apply PATH change
  shell: bash -c 'source /etc/profile'
