---
# tasks file for mongodb

- name: Update package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Download MongoDB package
  ansible.builtin.get_url:
    url: https://repo.mongodb.org/apt/ubuntu/dists/jammy/mongodb-org/8.0/multiverse/binary-amd64/mongodb-org-server_8.0.4_amd64.deb
    dest: /tmp/mongo.deb

- name: Install MongoDB package
  ansible.builtin.dpkg:
    deb: /tmp/mongo.deb

- name: Fix broken dependencies (if needed)
  ansible.builtin.apt:
    state: present
    update_cache: yes

- name: Replace MongoDB configuration file
  ansible.builtin.template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: mongodb
    group: mongodb
    mode: '0644'

- name: Start MongoDB service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: Allow MongoDB on port 27017 in UFW
  ansible.builtin.ufw:
    rule: allow
    port: 27017
    proto: tcp
