---
- name: Update the system
  command: sudo apt update

- name: Ensure Kafka dependencies are installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-11-jdk

- name: Download Kafka
  get_url:
    url: "{{ kafka_download_url }}"
    dest: /tmp/kafka.tgz

- name: Extract Kafka
  unarchive:
    src: /tmp/kafka.tgz
    dest: /opt/
    remote_src: yes

- name: Generate uuid
  command: KAFKA_CLUSTER_ID="$(bin/kafka-storage.sh random-uuid)"  

- name: Add uuid to configurations
  command: bin/kafka-storage.sh format --standalone -t $KAFKA_CLUSTER_ID -c config/kraft/reconfig-server.properties

- name: Create Kafka systemd service file
  become: true
  template:
    src: "kafka.service.j2"
    dest: "/etc/systemd/system/kafka.service"

- name: Reload systemd
  become: true
  command: systemctl daemon-reload

- name: Enable and start Kafka service
  become: true
  systemd:
    name: kafka
    state: started
    enabled: yes

- name: Wait for Kafka to start
  wait_for:
    host: "ansible_host"
    port: "{{ kafka_port }}"
    state: started
    delay: 10
    timeout: 60

- name: Create Kafka topic {{ topic_name }}
  become: true
  command:
    cmd: "{{ kafka_install_dir }}/bin/kafka-topics.sh --create --topic {{ topic_name }} --bootstrap-server {{ ansible_host }}:{{ kafka_port }} --partitions 1 --replication-factor 1"
    creates: "{{ kafka_log_dirs }}/{{ topic_name }}"
