---
# tasks file for app-host

- name: Update the system
  apt:
    update_cache: yes

- name: Install necessary dependencies
  apt:
    name:
      - python3-pip
      - curl
    state: present
    update_cache: yes

- name: Ensure kafka-python module is installed
  pip:
    name: kafka-python
    executable: /usr/bin/pip3

- name: Copy the Kafka producer script
  template:
    src: kafka_producer.py.j2
    dest: /opt/kafka_producer.py
    mode: '0755'

- name: Ensure the script has correct permissions
  file:
    path: /opt/kafka_producer.py
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Stop any existing Kafka producer process
  shell: |
    pkill -f "/usr/bin/python3 /opt/kafka_producer.py" || true
  ignore_errors: true

- name: Run Kafka producer script in the background
  shell: |
    nohup /usr/bin/python3 /opt/kafka_producer.py > /var/log/kafka_producer.log 2>&1 &
  args:
    executable: /bin/bash

- name: Ensure Kafka producer script is running
  shell: |
    pgrep -f "/usr/bin/python3 /opt/kafka_producer.py"
  register: producer_status
  retries: 3
  delay: 5
  until: producer_status.rc == 0
