---
# tasks file for app-host
- name: Update the system
  apt:
    update_cache: yes

- name: Installing pip
  become: true
  package:
    name: python3-pip
    state: present
- name: Install required Python packages
  pip:
    name:
      - kafka-python
      - requests

- name: Deploy Producer script
  template:
    src: producer.py.j2
    dest: /opt/producer.py
    mode: '0755'

- name: Create systemd service for Producer
  template:
    src: producer.service.j2
    dest: /etc/systemd/system/producer.service
  notify:
    - reload producer

- name: Reload systemd to register Producer service
  command: systemctl daemon-reload

- name: Enable Producer service to start on boot
  command: systemctl enable producer

- name: Start Producer service
  command: systemctl start producer
