---
# tasks file for app-host
- name: Update the system
  apt:
    update_cache: yes
    
- name: Install necessary dependencies
  apt:
    name:
      - python3-pip
      - python3-kafka
      - curl
    state: present
    update_cache: yes

- name: Copy the Kafka producer script
  copy:
    src: kafka_producer.py.j2
    dest: /opt/kafka_producer.py
    mode: '0755'

- name: Create a systemd service to run the script
  template:
    src: kafka_producer.service.j2
    dest: /etc/systemd/system/kafka_producer.service

- name: Start and enable Kafka producer service
  systemd:
    name: kafka_producer
    state: started
    enabled: yes

