---
- name: Import MongoDB public GPG key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-6.0.asc
    state: present

- name: Add MongoDB repository to sources list
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present

- name: Update MongoDB configuration
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf

- name: Start MongoDB service
  systemd:
    name: mongod
    state: started

- name: Enable MongoDB to start on boot
  systemd:
    name: mongod
    enabled: yes

- name: Create a database named Weather
  command: mongosh --eval "db.getSiblingDB('weather').createCollection('weather_data')"
  args:
    warn: false
