---
# tasks file for connect-api

- name: Ensure the Kafka libs directory exists
  file:
    path: "{{ kafka_dir }}/libs"
    state: directory
    mode: '0755'

- name: Install MongoDB Kafka Connector
  get_url:
    url: "https://repo1.maven.org/maven2/org/apache/kafka/connect-api/3.9.0/connect-api-3.9.0-javadoc.jar"
    dest: "{{ kafka_dir }}/libs/mongodb-kafka-connect-{{ connector_version }}.jar"

- name: Ensure the Kafka Connect plugin path is configured
  lineinfile:
    path: "{{ kafka_dir }}/config/connect-standalone.properties"
    regexp: '^plugin.path='
    line: "plugin.path={{ kafka_dir }}/libs"
    create: yes

- name: Create Kafka Connect MongoDB Sink connector configuration
  template:
    src: API-to-mongo.properties.j2
    dest: "{{ kafka_dir }}/config/API-to-mongo.properties"

- name: Start Kafka Connect in standalone mode
  command: >
    {{ kafka_dir }}/bin/connect-standalone.sh {{ kafka_dir }}/config/connect-standalone.properties {{ kafka_dir }}/config/API-to-mongo.properties
  async: 30
  poll: 0
