---
# tasks file for connect-api

- name: Update the system
  apt:
    update_cache: yes

- name: Install necessary dependencies
  apt:
    name:
      - python3-pip
      - curl
      - libssl-dev
    state: present
    update_cache: yes

- name: Ensure kafka-python module is installed
  pip:
    name: kafka-python
    executable: /usr/bin/pip3

- name: Ensure pymongo module is installed
  pip:
    name: pymongo
    executable: /usr/bin/pip3

- name: Copy the Kafka consumer script
  template:
    src: kafka_consumer.py.j2
    dest: /opt/kafka_consumer.py
    mode: '0755'

- name: Ensure the script has correct permissions
  file:
    path: /opt/kafka_consumer.py
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Run Kafka consumer script in the background
  shell: |
    nohup /usr/bin/python3 /opt/kafka_consumer.py > /var/log/kafka_consumer.log 2>&1 &
  args:
    executable: /bin/bash

- name: Ensure Kafka consumer script is running
  shell: |
    pgrep -f "/usr/bin/python3 /opt/kafka_consumer.py"
  register: consumer_status
  retries: 3
  delay: 5
  until: consumer_status.rc == 0
